spring:
    datasource:
        url: jdbc:postgresql://postgres_database:5432/server_db
        username: username
        password: password
        hikari:
            maximum-pool-size: 4
    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        root: DEBUG